### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by finn-raft** [finn-raft/PomodoroNavi#27]
## 各種情報
PomodoroNavi
https://pomodoronavi.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ポモドーロ作業タイマー（スタート【25分】、一時停止、停止）
  - タイマーが0:00になるとリダイレクトで休憩タイマーページに遷移し、休憩タイマーを開始する
- [x] 休憩タイマー（スタート【5分】、一時停止、停止）
  - タイマーが0:00になるとリダイレクトでポモドーロ作業タイマーページに遷移し、次のポモドーロ作業タイマーを開始する
- [x] タイマー切替時のアラーム音 

## READMEレビュー時から変更した機能
- ブラウザタブにタイマーのカウントダウンを表示

ポモドーロタイマー以外の機能はまだ実装していません。

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/740375d07c8dd7473fbaa88d789621f1.png)](https://gyazo.com/740375d07c8dd7473fbaa88d789621f1)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
