### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by finn-raft** [finn-raft/PomodoroNavi#6]
### 概要
PomodoroNaviのissueを制作しましたので、ご確認お願いします。

### 実装予定の機能
- [x] ユーザー登録機能
- [x] ログイン・ログアウト機能
- [x] ナビキャラクターの画像アップロード機能
- [x] ナビキャラクターとのチャット機能
- [x] ポモドーロタイマー機能
- [x] タイマーの設定変更機能
  - ポモドーロ作業時間の変更
  - 休憩時間の変更
  - 長い休憩時間【初期設定：15分】の変更
  - 長い休憩時間までのポモドーロ回数【初期設定：4回】の変更
  - 作業（休憩）タイマーを自動で開始するON/OFF機能
  - タイマー終了時のアラームON/OFF機能
- [x] アプリの背景色変更機能
- [x] レポート機能（本日・週間・月間・年間のポモドーロ作業時間グラフ表示＋累計の作業時間）
- [x] X（旧Twitter）へのシェア機能
- [x] パスワードリセット機能
- [x] アカウント削除機能
- [x] レスポンシブ対応

### 必要なページ
- [x] トップページ（ポモドーロタイマー機能・ナビキャラクターとのチャット機能）
- [x] 設定ページ
- [x] ログインページ
- [x] パスワード再申請ページ
- [x] パスワード再設定ページ
- [x] 新規ユーザー登録ページ
- [x] ナビキャラクター登録ページ
- [x] レポートページ
- [x] マイページ（プロフィール）
- [x] マイページ（ナビ）
- [x] マイページ（アカウント削除）
- [x] 利用規約ページ
- [x] プライバシーポリシーページ
- [x] お問合せフォーム（Googleフォーム使用）

**Comment by Tsuchiya2** [comment]
![image](https://github.com/finn-raft/PomodoroNavi/assets/61481161/9eef7f90-a6dd-4839-905f-425b58b07a7d)

Projectsにアクセスしましたが、看板・issue・ストーリーポイントの確認ができませんでした。
カリキュラムをご確認の上、上記が確認できる状態でのご提出をお願いいたします。

**Comment by finn-raft** [comment]
ご確認ありがとうございます。
すみません、ProjectsをLinkし忘れてました……。
先ほど確認できるように設定しましたので、宜しくお願い致します。

**Comment by finn-raft** [comment]
ご確認ありがとうございます。
ご指摘いただいた点に関してissueを細分化いたしました。
再度ご確認宜しくお願い致します。

**Comment by ky0613** [comment]
対応ありがとうございます。
概ね良いかと思います！LGTMです！
